includes:
  - configs/detection/base/globals.yaml
  - configs/detection/data/aim.yaml
  - configs/detection/base/transform.yaml
  - configs/detection/models/detr_custom.yaml

model:
  name: DETRCustomBackbone
  args:
    model_name: detr
    backbone_name: tf_efficientnet_b0
    num_queries: 10
    min_conf: 0.25
    hidden_dim: 256
    position_embedding: sine
    freeze_backbone: false
    dilation: false
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 6
    dec_layers: 6
    pre_norm: false
    aux_loss: true

optimizer:
  name: AdamW
  args:
    lr: [0.000001, 0.001]
scheduler: null

trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 5000
    clip_grad: null
    evaluate_interval: 0
    use_fp16: false
callbacks: 
  - name: WandbCallbacks
    args:
      username: hcmus-dcu
      project_name: aim
      group_name: optuna
      reinit: True

optuna:
  float:
    - optimizer.args.lr
