augmentations:
  train:
    name: DetCompose
    args:
      transforms:
        - name: DetCompose
          args:
            transforms:
              - name: BoxOrder
                args:
                  order: xywh2xyxy
        - name: AlbCompose
          args:
            bbox_params: 
              name: AlbBboxParams
              args: 
                format: 'pascal_voc' 
                min_area: 0 
                min_visibility: 0
                label_fields: ['class_labels']
            transforms:
              - name: AlbResize
                args:
                  width: 512
                  height: 512
              - name: AlbHorizontalFlip
              - name: AlbShiftScaleRotate
                args:
                  scale_limit: 0.1
                  rotate_limit: 10
              - name: AlbGaussianBlur
              - name: AlbRandomBrightnessContrast
                args:
                  brightness_limit:     0.1
                  contrast_limit:       0.1 
              - name: AlbToTensorV2
  val:
    name: DetCompose
    args:
      transforms:
        - name: DetCompose
          args:
            transforms:
              - name: BoxOrder
                args:
                  order: xywh2xyxy
        - name: AlbCompose
          args:
            bbox_params: 
              name: AlbBboxParams
              args: 
                format: 'pascal_voc' 
                min_area: 0 
                min_visibility: 0
                label_fields: ['class_labels']
            transforms:
              - name: AlbResize
                args:
                  width: 512
                  height: 512
              - name: AlbToTensorV2

  test:
    name: AlbCompose
    args:
      transforms:
        - name: AlbResize
          args:
            width: 512
            height: 512
        - name: AlbToTensorV2