includes:
  - configs/classification/base/globals.yaml
  - configs/classification/base/optimizer.yaml
  - configs/classification/base/transform.yaml
  - configs/classification/data/vocals.yaml

model:
  name: VOFO_DETR
  args:
    clf_name: null #efficientnet_b0
    detr_name: efficientnet_b0
    clf_checkpoint: ./weights/tf_efficientnetb0_vocal_0/checkpoints/best.pth
    clf_freeze: False
    detr_checkpoint: null
    pooling_type: attn
    num_heads: 4

    detr_num_queries: 10
    detr_min_conf: 0.1
    detr_hidden_dim: 256
    detr_position_embedding: sine
    detr_freeze_backbone: false
    detr_dilation: false
    detr_dropout: 0.1
    detr_nheads: 8
    detr_dim_feedforward: 2048
    detr_enc_layers: 6
    detr_dec_layers: 6
    detr_pre_norm: false
loss:
  name: ClassificationCELoss