global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: ./configs/detection/transform.yaml
  save_dir: /runs
  device: cuda:0
  pretrained: https://dl.fbaipublicfiles.com/detr/detr-r101-dc5-a2e86def.pth
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 0.1
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
  - name: WandbCallbacks
    args:
      username: kaylode
      project_name: isbi-detection 
  - name: DetectionVisualizerCallbacks
model:
  name: DETRConvnext
  args:
    model_name: detr
    backbone_name: resnet50
    hidden_dim: 256
    position_embedding: sine
    freeze_backbone: false
    dilation: true
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 6
    dec_layers: 6
    pre_norm: True
loss:
  name: DETRLosses
  args:
    loss_ce: 1
    loss_bbox: 5
    loss_giou: 2
    loss_mask: null
    loss_dice: null
    cost_class: 1
    cost_bbox: 5
    cost_giou: 2
    eos_coef: 0.1
metrics: 
  - name: DetectionPrecisionRecall
    args: 
       min_conf: 0.2
       min_iou: 0.5
       eps: 1e-6
optimizer:
  name: AdamW
  args:
    lr: 0.0001
    weight_decay: 0.0005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: COCODataset
      args:
        image_dir: /content/data/aihcm20/images
        label_path: /content/data/aihcm20/annotations/annotations_train.json
        txt_classnames: /content/data/aihcm20/classnames.txt

    val:
      name: COCODataset
      args:
        image_dir: /content/data/aihcm20/images
        label_path: /content/data/aihcm20/annotations/annotations_val.json
        txt_classnames: /content/data/aihcm20/classnames.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: true
        shuffle: true
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: false
        shuffle: false