global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: ./configs/detection/transform.yaml
  save_dir: /runs
  device: cuda:0
  pretrained: null #weights/detr-r50-e632da11.pth
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 100000
    clip_grad: 0.1
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: false
callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: f1_score
  - name: DetectionVisualizerCallbacks
    args:
      order: cxcywh2xyxy
  - name: WandbCallbacks
    args:
      username: kaylode
      project_name: vocal-folds-aim
  - name: TensorboardCallbacks
model:
  name: DETRConvnext
  args:
    model_name: detr
    backbone_name: convnext_base
    num_queries: 10
    min_conf: 0.25
    hidden_dim: 256
    position_embedding: sine
    freeze_backbone: false
    dilation: false
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 6
    dec_layers: 6
    pre_norm: false
    aux_loss: true
loss:
  name: DETRLosses
  args:
    loss_ce: 1
    loss_bbox: 5
    loss_giou: 2
    loss_mask: null
    loss_dice: null
    cost_class: 1
    cost_bbox: 5
    cost_giou: 2
    eos_coef: 0.1
metrics: 
  - name: MeanAveragePrecision
    args: 
       min_iou: 0.3
optimizer:
  name: AdamW
  args:
    lr: 0.0003
    weight_decay: 0.0001
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: multistep
    milestones: [40000, 70000]
    gamma: 0.1
data:
  dataset:
    train:
      name: VocalDetectionDataset
      args:
        image_dir: data/aim/images/Train_4classes
        label_path: data/aim/annotations/annotation_0_train.json
    val:
      name: VocalDetectionDataset
      args:
        image_dir: data/aim/images/Train_4classes
        label_path: data/aim/annotations/annotation_0_val.json
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: true
        shuffle: true
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: false
        shuffle: true