global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: ./configs/detection/transform.yaml
  save_dir: /runs
  device: cuda:0
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
    args: null
model:
  name: DETRConvnext
  args:
    model_name: detr
loss:
  name: DETRLosses
metrics:
  - name: PixelAccuracy
    args:
      ignore_index: 0
  - name: DiceScore
    args:
      ignore_index: 0
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: COCODataset
      args:
        image_dir: /content/data/aihcm20/images
        label_path: /content/data/aihcm20/annotations/annotations_train.json
        txt_classnames: /content/data/aihcm20/classnames.txt

    val:
      name: COCODataset
      args:
        image_dir: /content/data/aihcm20/images
        label_path: /content/data/aihcm20/annotations/annotations_val.json
        txt_classnames: /content/data/aihcm20/classnames.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: true
        shuffle: false
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: false
        shuffle: true