train:
  name: AlbCompose
  args:
    bbox_params: 
      name: AlbBboxParams
      args: 
        format: 'pascal_voc' 
        min_area: 0 
        min_visibility: 0
        label_fields: ['class_labels']
    transforms:
      - name: BoxOrder
        args: 
          order: xywh2xyxy
      - name: AlbResize
        args:
          width: 256
          height: 256
      - name: AlbHorizontalFlip
        args:
      - name: AlbGaussianBlur
        args:
      - name: AlbHueSaturationValue
        args:
          hue_shift_limit:       0.2
          sat_shift_limit:       0.2
          val_shift_limit:       0.2
      - name: AlbRandomBrightnessContrast
        args:
          brightness_limit:     0.3
          contrast_limit:       0.3
      - name: AlbNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - name: AlbToTensorV2
val:
  name: AlbCompose
  args:
    bbox_params: 
      name: AlbBboxParams
      args: 
        format: 'pascal_voc' 
        min_area: 0 
        min_visibility: 0
        label_fields: ['class_labels']
    transforms:
      - name: BoxOrder
        args: 
          order: xywh2xyxy
      - name: AlbResize
        args:
          width: 256
          height: 256
      - name: AlbNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - name: AlbToTensorV2