optimizer:
  name: AdamW
  args:
    lr: 0.001
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 50
    t_mul: 0.99
    eta_mul: 0.99
    eta_min: 1.0e-06