includes:
  - configs/classification/base/globals.yaml
  - configs/classification/base/optimizer.yaml
  - configs/classification/base/transform.yaml
  - configs/classification/data/kvasir.yaml

model:
  name: Resnet
  args:
    model_name: resnet50
loss:
  name: ClassificationCELoss