global:
  exp_name: null
  exist_ok: false
  debug: True
  cfg_transform: configs/sample/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null

model:
  name: MedTEXFramework
  args:

data:
  dataset:
    name: ImageDataset
    args:
      image_dir: data/images
      txt_classnames: configs/classification/classes.txt

  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 16
      drop_last: False
      shuffle: False
