train:
  name: TVCompose
  args:
    transforms:
      - name: TVResize
        args:
          size: [256, 256]
      - name: TVRandomResizedCrop
        args:
          size: [224, 224]
      - name: TVRandomAffine
        args:
          degrees: 10
          translate: [0.1, 0.2]
          scale: [0.8, 1.0]
          shear: 5
      - name: TVToTensor
      - name: TVNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
val:
  name: TVCompose
  args:
    transforms:
      - name: TVResize
        args:
          size: [256, 256]
      - name: TVToTensor
      - name: TVNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]