global:
  exp_name: medtex_ersgan_1
  exist_ok: false
  debug: true
  cfg_transform: configs/transform.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
  stage: normal
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 30000
    clip_grad: 10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
    args: null
  - name: CheckpointCallbacks
    args:
      best_key: bl_acc
  - name: ClassificationVisualizerCallbacks
    args: null
  - name: WandbCallbacks
    args:
      username: vocal-fold-isbi
      project_name: vocal-fold-isbi
model:
  name: MedTEXFramework
  args:
loss:
  name: ClassificationCELoss
metrics:
  - name: Accuracy
    args: null
  - name: BalancedAccuracyMetric
    args: null
  - name: F1ScoreMetric
    args:
      average: weighted
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.00005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 50
    t_mul: 0.99
    eta_mul: 0.99
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: ClassificationCSVDataset
      args:
        image_dir: data/ersgan
        csv_path: data/csvs/output_1_train.csv
        txt_classnames: configs/classes.txt
    val:
      name: ClassificationCSVDataset
      args:
        image_dir: data/ersgan
        csv_path: data/csvs/output_1_val.csv
        txt_classnames: configs/classes.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: true
        shuffle: false
        sampler:
          name: BalanceSampler
          args:
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: false
        shuffle: true