includes:
  - configs/detection/base/globals.yaml
  - configs/detection/base/optimizer.yaml
  - configs/detection/data/aim_plus1.yaml
  - configs/detection/base/transforms/transform_effdet.yaml

model:
  name: EffDet
  args:
      model_name: efficientdet
      weights: DEFAULT
      architecture: resnet50
      drop_path_rate: 0.2
      soft_nms: False
      pretrained_backbone: True
      min_conf: 0.1
loss: null

callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: mAP_0.5:0.95
  - name: DetectionVisualizerCallbacks
    args:
      order: null #xyxy
      mean: [0,0,0]
      std: [1,1,1]
  - name: WandbCallbacks
    args:
      username: hcmus-dcu
      project_name: aim
      group_name: detection-tuned
      tags: ['efficientdet', 'detection']