includes:
  - configs/detection/base/globals.yaml
  - configs/detection/base/optimizer.yaml
  - configs/detection/data/aim.yaml
  - configs/detection/base/transform_faster_rcnn.yaml

model:
  name: FasterRCNN
  args:
      model_name: faster_rcnn
      weights: DEFAULT
loss: null

callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: f1_score
  - name: DetectionVisualizerCallbacks
    args:
      order: cxcywh2xyxy
      mean: [0,0,0]
      std: [0,0,0]
  # - name: WandbCallbacks
  #   args:
  #     username: kaylode
  #     project_name: vocal-folds-aim
  #     group_name: detection
  - name: TensorboardCallbacks

data:
  dataset:
    train:
      name: VocalDetectionDataset
      args:
        image_dir: data/aim/images/Train_4classes
        label_path: data/aim/annotations/annotation_0_train.json
    val:
      name: VocalDetectionDataset
      args:
        image_dir: data/aim/images/Train_4classes
        label_path: data/aim/annotations/annotation_0_val.json
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 4
        drop_last: true
        shuffle: true
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 4
        drop_last: false
        shuffle: true