includes:
  - configs/detection/base/globals.yaml
  - configs/detection/base/optimizer.yaml
  - configs/detection/data/aim.yaml
  - configs/detection/base/transform_faster_rcnn.yaml

model:
  name: FasterRCNN
  args:
      model_name: fasterrcnn
      weights: DEFAULT
loss: null

callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: f1_score
  - name: DetectionVisualizerCallbacks
    args:
      order: cxcywh2xyxy
      mean: [0,0,0]
      std: [0,0,0]
  - name: WandbCallbacks
    args:
      username: hcmus-dcu
      project_name: aim
      group_name: detection
  - name: TensorboardCallbacks