includes:
  - configs/detection/base/globals.yaml
  - configs/detection/base/optimizer.yaml
  - configs/detection/data/aim.yaml
  - configs/detection/base/transforms/transform_frcnn.yaml

model:
  name: FasterRCNN
  args:
      model_name: faster_rcnn
      weights: DEFAULT
loss: null

callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: mAP_0.5:0.95
  - name: DetectionVisualizerCallbacks
    args:
      order: cxcywh2xyxy
      mean: [0,0,0]
      std: [1,1,1]
  # - name: WandbCallbacks
  #   args:
  #     username: hcmus-dcu
  #     project_name: aim
  #     group_name: detection