global:
  exp_name: null
  exist_ok: false
  debug: true
  save_dir: ./runs
  device: cuda:0
  pretrained: null
  resume: null
  weights: null
  seed: 1702
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 50000
    clip_grad: 0.1
    evaluate_interval: 1
    use_fp16: false
callbacks:
  - name: TorchCheckpointCallbacks
    args:
      best_key: f1_score
  - name: DetectionVisualizerCallbacks
    args:
      order: cxcywh2xyxy
      # mean: [0.5, 0.5, 0.5]
      # std: [0.5, 0.5, 0.5]
  - name: WandbCallbacks
    args:
      username: hcmus-dcu
      project_name: aim
      group_name: detection
      tags: detection
  - name: TensorboardCallbacks
metrics: 
  - name: MeanAveragePrecision