global:
  exp_name: null
  exist_ok: false
  debug: true
  save_dir: ./runs
  device: cuda:0
  pretrained: null
  resume: null
  weights: null
  seed: 1702
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 50000
    clip_grad: 0.1
    evaluate_interval: 1
    use_fp16: false
metrics: 
  - name: MeanAveragePrecision