optimizer:
  name: AdamW
  args:
    lr: 1.0e-05
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: multistep
    milestones:
    # - 5000
    - 12500
    # - 25000
    # - 40000
    gamma: 0.5