settings:
  #################   DATASET CONFIG   ###################

  train_imgs: "/content/data/COVIDx/images"
  val_imgs: "/content/data/COVIDx/images"
  train_txt: "/content/data/COVIDx/train_COVIDx9A.txt"
  val_txt: "/content/data/COVIDx/test_COVIDx9A.txt"
  
  #################   TRAINING CONFIG   ###################
  
  model_name: 'covidnet' #[vit_base_patch16_384]
  loss_fn: 'focal' #[ce | focal]

  # pretrained_backbone: ''                  # Pretrained backbone
  
  gpu_devices: '0'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 64
  num_workers: 2
  
  image_size: 256               # should be square to prevent bugs [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

  # gradient accumulation
  mixed_precision: True                # whether to use nvidia apex
  total_accumulate_steps: 0           # step * batch_size, not use if equal 0
